import intf_libs = gtest%lib{gtest}

pub = [dir_path] ../include/gmock
include $pub
pub_hdrs = $($pub/pub_hdrs)

# Build options.
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc" "-I$src_root"
cxx.poptions += $($intf_libs: cxx.export.poptions)                

lib{gmock}: $pub/{$pub_hdrs}
# lib{gmock}: cxx{gmock-all} $intf_libs libul{gtest-util}
# libul{gtest-util}: cxx{gtest-port gtest-death-test gtest} hxx{**} $intf_libs
# if ($cxx.id == 'msvc')
# {
#   # Hack around msvc to get around symbols exporting
#   objs{gmock-all}: cxx.poptions += -DGTEST_API_='__declspec(dllexport)'
#   objs{gtest-port}: cxx.poptions += -DGTEST_API_='__declspec(dllexport)'
#   objs{gtest-death-test}: cxx.poptions += -DGTEST_API_='__declspec(dllexport)'
#   objs{gtest}: cxx.poptions += -DGTEST_API_='__declspec(dllexport)'
# }
# lib{gmock}: cxx{gmock-all} $impl_libs
lib{gmock}: obj{gmock-all}
obj{gmock-all}: cxx{gmock-all}
objs{gmock-all}: cxx.poptions += -DGTEST_CREATE_SHARED_LIBRARY=1
# gtest-port is part of gtest which is coupled into gmock
# Need to ensure to compile this part and not export any symbols from it
obj{gtest-port}: cxx{gtest-port} h{**}
objs{gtest-port}: cxx.poptions += -DGTEST_API_=''
libul{gtest}: obj{gtest-port} $intf_libs
lib{gmock}: libul{gtest}                        
lib{gmock}: cxx.export.poptions += $($intf_libs: cxx.export.poptions) \
                                    "-I$out_pfx_inc" "-I$src_pfx_inc"

liba{gmock_main}: cxx{gmock_main}
liba{gmock_main}: bin.whole = true
liba{gmock_main}: cxx.export.libs += lib{gmock}

./: lib{gmock} liba{gmock_main}